# Generated by Django 4.0.3 on 2022-04-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0007_auto_20220303_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='ind_pri',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='tot_pri',
            field=models.CharField(max_length=50),
        ),
    ]
