# Generated by Django 4.0.3 on 2022-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furniture', '0010_alter_iteminfo_pur_from_alter_iteminfo_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminfo',
            name='Pur_from',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='order_ref',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='iteminfo',
            name='spec',
            field=models.CharField(max_length=10000),
        ),
    ]
