# Generated by Django 3.2.8 on 2022-03-13 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resources', '0005_faculty_joiningdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_info',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('qty', models.PositiveIntegerField(default=1)),
                ('tot_qty', models.PositiveIntegerField(default=1)),
                ('Pur_from', models.CharField(max_length=50)),
                ('order_ref', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('in_no', models.PositiveIntegerField()),
                ('spec', models.CharField(max_length=50)),
                ('warn', models.DateField()),
                ('ind_pri', models.PositiveIntegerField()),
                ('tot_pri', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='img/%y')),
                ('auth', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Replace_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('added_by', models.CharField(max_length=50)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info')),
            ],
        ),
        migrations.CreateModel(
            name='Remove_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('added_by', models.CharField(max_length=50)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info')),
            ],
        ),
        migrations.CreateModel(
            name='Maintain_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('given', models.CharField(max_length=50)),
                ('add_date', models.DateField()),
                ('added_by', models.CharField(max_length=50)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info')),
            ],
        ),
        migrations.CreateModel(
            name='Assign_item_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('lab_name', models.CharField(max_length=50, null='True')),
                ('assigned_by', models.CharField(max_length=50)),
                ('assign_date', models.DateField()),
                ('faculty', models.ForeignKey(null='True', on_delete=django.db.models.deletion.DO_NOTHING, to='Resources.faculty')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hardware.item_info')),
            ],
        ),
    ]
