# Generated by Django 4.0.3 on 2022-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='ind_pri',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='tot_pri',
            field=models.CharField(max_length=50),
        ),
    ]
