# Generated by Django 4.0.3 on 2022-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_alter_item_info_ind_pri_alter_item_info_tot_pri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='in_no',
            field=models.CharField(max_length=50),
        ),
    ]
