# Generated by Django 4.0.3 on 2022-04-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_alter_item_info_in_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_info',
            name='Pur_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='in_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='order_ref',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item_info',
            name='spec',
            field=models.CharField(max_length=500),
        ),
    ]
