# Generated by Django 3.2.8 on 2022-02-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
