# Generated by Django 3.2.8 on 2022-02-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thesis', '0003_thesis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
