# Generated by Django 4.1.7 on 2024-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0005_faculty_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='MidTerm1Total',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='marks',
            name='MidTerm2Total',
            field=models.IntegerField(default=20),
        ),
    ]
