# Generated by Django 4.2.13 on 2025-02-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0006_alter_marks_midterm1total_alter_marks_midterm2total'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Password',
            field=models.CharField(default='mnb098', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default='abc123', max_length=128),
        ),
    ]
