# Generated by Django 4.0.3 on 2022-04-12 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0011_alter_software_manage_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='software_info',
            name='Pur_from',
            field=models.CharField(default=datetime.date.today, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_info',
            name='in_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_info',
            name='order_date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_info',
            name='order_ref',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_info',
            name='spec',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_info',
            name='tot_pri',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software_info',
            name='ind_pri',
            field=models.CharField(max_length=50),
        ),
    ]
