# Generated by Django 4.0.3 on 2022-04-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Software', '0012_software_info_pur_from_software_info_in_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_info',
            name='PurForSub',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='Pur_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='SName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='in_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='order_ref',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software_info',
            name='spec',
            field=models.CharField(max_length=500),
        ),
    ]
